#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  float illuminance;
  float humidity;
  bool ledOn;
  float temperature;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include <SPI.h>
#include <WiFiNINA.h>          
#include <utility/wifi_drv.h>
#include "thingProperties.h"
#include <Arduino_MKRENV.h>

#define LEDPIN 26


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  
  if (!ENV.begin()) {
    Serial.println("Failed to initialize MKR ENV shield!");
    while (1);
  }

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  WiFiDrv::pinMode(LEDPIN, OUTPUT);
}

void loop() {
  ArduinoCloud.update();
  temperature = ENV.readTemperature(FAHRENHEIT);
  humidity    = ENV.readHumidity();
  //float pressure    = ENV.readPressure(PSI);
  illuminance = ENV.readIlluminance(FOOTCANDLE);
}





void onLedOnChange() {
  if (ledOn == true) {
    WiFiDrv::digitalWrite(LEDPIN, HIGH);
  }
  else {
    WiFiDrv::digitalWrite(LEDPIN, LOW);
  }
  
}













